debugf :
	g++ -g ./connection_pool/connection_pool.hpp ./async_thread_pool/async_thread_pool.hpp ./log/log.hpp ./http_conn/http_conn.hpp main.cpp -std=c++23 -l dl -l mysqlclient -l jsoncpp  -l pthread -o main

.PHONY : debugf
