debugf :
	g++ -g main.cpp HttpServer01.cpp HttpServer01.hpp ./Log/*.h ./Log/*.cpp -std=c++11 -pthread -l jsoncpp -o HttpServer

.PHONY : debugf
#  -l mysqlclient -l dl ./ThreadPool/*.cpp ./ThreadPool/*.hpp